# Backstage override configuration for your local development environment
proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  endpoints:
    '/kroki':
      target: 'http://kroki-core'
      changeOrigin: true
